services:
  grafana:
    build: .
    container_name: grafana-sqlite
    ports:
      - "3000:3000"
    user: "0"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - /home/jemima/Documentos/proyecto-1/Daemon/containers.db:/db/containers.db:ro  # apunta a daemon/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=frser-sqlite-datasource